config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get '/import_users', to: 'users#import_users'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'rest-client'
  require 'open-uri'

  def index
    @users = User.page params[:page]
  end

  def show
    @user = User.find(params[:id])
  end

  def get_user_pic(picture, username, size)
    IO.copy_stream(URI.parse(picture).open, "./public/images/users-#{size}/#{username}.jpg")
  end

  def import_users
    url = 'https://randomuser.me/api/?results=30'

    JSON.parse(RestClient.get(url))['results'].map do |user|
      User.create(data: user)
      picture = user['picture']
      username = user['login']['username']
      get_user_pic(picture['large'], username, 'large')
      get_user_pic(picture['medium'], username, 'medium')
      get_user_pic(picture['thumbnail'], username, 'thumbnail')
    end

    render json: User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsUserList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Rails User List</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Import Users', import_users_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'List Users', users_path, class: 'nav-link active' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h2>All users: </h2>

<table class="table table-striped">
  <thead >
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Username</th>
      <th>email</th>
      <th colspan="5"></th>
    </tr>
  </thead> 
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
            <img src="<%= '/images/users-thumbnail/' + user[:data]['login']['username'] + '.jpg' %>" alt="" />
        </td>
        <td>
          <%= user[:data]["name"]["first"]%>
          <%= user[:data]["name"]["last"]%>
        </td>
        <td>
          <%= user[:data]["login"]["username"]%>
        </td>
        <td>
          <%= user[:data]["email"]%>
        </td>
        <td>
          <%= link_to 'Show', user_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= paginate @users, theme: 'bootstrap-5', pagination_class: "pagination-centered"  %>
</div>

app/views/users/show.html.erb
<h3>User: <%= @user[:data]["login"]["username"]%></h3>

<div class="card" style="width: 18rem;">
  <img src="<%= '../images/users-large/' + @user[:data]['login']['username'] + '.jpg' %>" alt="" />
  <div class="card-body">
  <h4 class="card-title">
    <%= @user[:data]["name"]["first"]%>
    <%= @user[:data]["name"]["last"]%>
  </h4>
  <p>Age: 
    <%= @user[:data]["dob"]["age"]%>
  </p>
  <p>Email:
    <%= @user[:data]["email"]%>
  </p>
  <p>Phone:
    <%= @user[:data]["phone"]%>
  </p>
  <p>Cell:
    <%= @user[:data]["cell"]%>
  </p>

  <p>Adress:
    <%= @user[:data]["location"]["street"]["name"]%>,
    <%= @user[:data]["location"]["street"]["number"]%>,
    <%= @user[:data]["location"]["city"]%> -
    <%= @user[:data]["location"]["state"]%>, 
    <%= @user[:data]["location"]["country"]%>,
    <%= @user[:data]["location"]["postcode"]%>
  </p>
  </div>
</div>
<%= link_to 'Back', users_path %>